sudo: required
language: cpp

notifications:
  email:
  - schaffert@google.com
  - tomac@google.com
  - vrandecic@google.com
  - thomaspt@google.com

cache:
  apt: true
  directories:
  - cppcms-1.0.5
  - cppdb-0.3.1

before_install:
  - sudo apt-get install libboost-all-dev
  - mkdir download && cd download
  - wget http://downloads.sourceforge.net/project/cppcms/cppcms/1.0.5/cppcms-1.0.5.tar.bz2
  - wget http://downloads.sourceforge.net/project/cppcms/cppdb/1.3.1/cppdb-0.3.1.tar.bz2
  - cd ..
  - tar xjf download/cppdb-0.3.1.tar.bz2
  - tar xjf download/cppcms-1.0.5.tar.bz2

install:
  - mkdir -p cppcms-1.0.5/build && cd cppcms-1.0.5/build
  - cmake .. && make && sudo make install
  - cd ../..
  - mkdir -p cppdb-0.3.1/build && cd cppdb-0.3.1/build
  - cmake .. && make && sudo make install
  - cd ../..

script: sh -c 'cd backend && mkdir build && cd build && cmake .. && make && make test'
